export const authStyles = {
  input: {
    padding: "14px",
    fontSize: "16px",
    borderRadius: "12px",
    border: "1px solid #d1d5db",
    outline: "none",
  },
  button: {
    background: "#2f68e3",
    color: "white",
    border: "none",
    borderRadius: "12px",
    padding: "14px",
    fontSize: "18px",
    fontWeight: "600",
    cursor: "pointer",
    boxShadow: "0 6px 18px rgba(37,99,235,0.25)",
  },
  secondaryButton: {
    background: "#eef2ff",
    color: "#2f68e3",
    border: "1px solid #c7d2fe",
    borderRadius: "12px",
    padding: "12px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
  },
  text: {
    margin: 0,
    textAlign: "center",
    color: "#4b5563",
    fontSize: "15px",
  },
  link: {
    color: "#2f68e3",
    textDecoration: "none",
    fontWeight: "600",
  },
  error: {
    margin: 0,
    color: "#b91c1c",
    background: "#fee2e2",
    border: "1px solid #fecaca",
    borderRadius: "12px",
    padding: "12px",
    fontSize: "14px",
  },
  success: {
    margin: 0,
    color: "#065f46",
    background: "#d1fae5",
    border: "1px solid #a7f3d0",
    borderRadius: "12px",
    padding: "12px",
    fontSize: "14px",
  },
};